[build]
  publish = "site/"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=60"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
