"""
Piyasa Monitörü — Konfigürasyon (Yahoo Finance Only)
EVDS kaldırıldı. Tüm veriler Yahoo Finance'den.
"""

import os
import re
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)
TV_LOGO_BASE = "https://s3-symbol-logo.tradingview.com"

# Yahoo Finance → TradingView sembol eşlemesi (logo URL doğruluğu için)
# Sadece Yahoo Finance sembolü TradingView sembolünden farklı olanlar.
YAHOO_TO_TV = {
    # ── Enerji ──
    "BZ=F": "BRENT",
    "CL=F": "WTI",
    # ── Kıymetli Madenler ──
    "GC=F": "XAUUSD",
    "SI=F": "XAGUSD",
    "PL=F": "XPTUSD",
    "PA=F": "XPDUSD",
    # ── Sanayi ──
    "ZN=F": "ZNC",
    # ── Döviz ──
    "DX-Y.NYB": "DXY",
    # ── Tahvil Faizleri ──
    "^IRX": "US03MY",
    "2YY=F": "US02Y",
    "^FVX": "US05Y",
    "^TNX": "US10Y",
    "^TYX": "US30Y",
    # ── Endeksler ──
    "^GSPC": "SPX",
    "^IXIC": "NDX",
    "^STOXX50E": "SX5E",
    "^FTSE": "UKX",
    "^GDAXI": "DAX",
    "^FCHI": "PX1",
    "^N225": "NI225",
    "^BSESN": "SENSEX",
    "^KS11": "KOSPI",
    "^TWII": "TAIEX",
    "^MERV": "IMV",
    "^AXJO": "XJO",
    "^IBEX": "IBC",
    "000001.SS": "SHCOMP",
}

FOREX_COUNTRY_MAP = {
    "USD": "US", "EUR": "EU", "GBP": "GB", "TRY": "TR", "JPY": "JP", "CHF": "CH",
    "AUD": "AU", "CAD": "CA", "NZD": "NZ", "CNY": "CN", "BRL": "BR", "MXN": "MX",
    "INR": "IN", "ZAR": "ZA", "SEK": "SE", "NOK": "NO", "SGD": "SG", "THB": "TH",
    "KRW": "KR", "PLN": "PL", "HUF": "HU", "AED": "AE", "RUB": "RU", "SAR": "SA",
}


def _tv_symbol_candidates(symbol: str) -> list[str]:
    """TradingView için olası logo URL'lerini üret."""
    if not symbol:
        return []
    clean = symbol.strip()

    # Explicit Yahoo → TradingView mapping
    tv_sym = YAHOO_TO_TV.get(clean)
    if tv_sym:
        # Exchange prefix varsa (ör. BIST:GARAN)
        if ":" in tv_sym:
            exchange, ticker = tv_sym.split(":", 1)
            return [
                f"{TV_LOGO_BASE}/{exchange}-{ticker}.svg",
                f"{TV_LOGO_BASE}/{exchange}-{ticker}--big.svg",
                f"{TV_LOGO_BASE}/{ticker.lower()}.svg",
                f"{TV_LOGO_BASE}/{ticker.lower()}--big.svg",
            ]
        lower = tv_sym.lower()
        return [
            f"{TV_LOGO_BASE}/{lower}.svg",
            f"{TV_LOGO_BASE}/{lower}--big.svg",
        ]

    # Mapping'te yoksa mevcut mantık
    clean = clean.upper()
    base = clean
    if clean.endswith("=X"):
        base = clean[:-2]
    elif clean.endswith("=F"):
        base = clean[:-2]
    exchange = None
    suffix_exchange = {
        ".IS": "BIST",
        ".KS": "KRX",
        ".SS": "SSE",
        ".L": "LSE",
        ".PA": "EURONEXT",
        ".DE": "XETR",
        ".MI": "MIL",
        ".TO": "TSX",
    }
    for suffix, ex in suffix_exchange.items():
        if clean.endswith(suffix):
            exchange = ex
            base = clean[: -len(suffix)]
            break

    normalized = re.sub(r"[^A-Z0-9]", "", base)
    lower = normalized.lower()

    urls = []
    if exchange:
        urls.append(f"{TV_LOGO_BASE}/{exchange}-{normalized}.svg")
        urls.append(f"{TV_LOGO_BASE}/{exchange}-{normalized}--big.svg")
    urls.append(f"{TV_LOGO_BASE}/{lower}.svg")
    urls.append(f"{TV_LOGO_BASE}/{lower}--big.svg")
    return list(dict.fromkeys(urls))


def _tv_forex_pair(symbol: str) -> list[str]:
    """USDTRY=X gibi pariteler için ülke bayrağı ikonları."""
    head = symbol.split("=")[0].upper()
    if len(head) < 6:
        return []
    left, right = head[:3], head[3:6]
    c1 = FOREX_COUNTRY_MAP.get(left)
    c2 = FOREX_COUNTRY_MAP.get(right)
    if not c1 or not c2:
        return []
    return [
        f"{TV_LOGO_BASE}/country/{c1}--big.svg",
        f"{TV_LOGO_BASE}/country/{c2}--big.svg",
    ]


def tradingview_logo_meta(symbol: str, meta: dict) -> dict:
    """
    Sembol için logo metadata üretir.
    İstenirse config'ten `logo_url`, `logo_pair`, `logo_candidates` override edilebilir.
    """
    if meta.get("logo_url") or meta.get("logo_pair") or meta.get("logo_candidates"):
        return {
            "logo_url": meta.get("logo_url"),
            "logo_pair": meta.get("logo_pair"),
            "logo_candidates": meta.get("logo_candidates", []),
        }

    logo_pair = _tv_forex_pair(symbol) if symbol.endswith("=X") else []
    logo_candidates = _tv_symbol_candidates(symbol)

    if symbol.endswith("-USD"):
        coin = re.sub(r"\d", "", symbol.split("-")[0].upper())
        logo_candidates = [f"{TV_LOGO_BASE}/{coin.lower()}.svg"] + logo_candidates
        logo_candidates = list(dict.fromkeys(logo_candidates))

    return {
        "logo_url": logo_candidates[0] if logo_candidates else None,
        "logo_pair": logo_pair,
        "logo_candidates": logo_candidates,
    }
    
COMMODITIES_ENERGY = {
    "file": "commodities_energy.json",
    "category": "Enerji",
    "symbols": {
        "BZ=F":  {"name": "BZ (Brent)",        "unit": "USD/bbl"},
        "CL=F":  {"name": "CL (WTI)",           "unit": "USD/bbl"},
        "NG=F":  {"name": "NG (Doğalgaz)",  "unit": "USD/MMBtu"},
        "TTF=F": {"name": "TTF (Avrupa Gaz)", "unit": "EUR/MWh"},
        "HO=F":  {"name": "HO (Isıtma Yağı)",          "unit": "USD/gal"},
        "RB=F":  {"name": "RB (Benzin)",         "unit": "USD/gal"},
        "URA":   {"name": "URA (Uranyum ETF)",         "unit": "USD"},
        "KRBN":  {"name": "KRBN (Karbon Kredisi ETF)", "unit": "USD"},
        "USO":   {"name": "USO (Ham Petrol ETF)",      "unit": "USD"},
        "UNG":   {"name": "UNG (Doğalgaz ETF)",        "unit": "USD"},
        "XLE":   {"name": "XLE (Enerji Sektörü ETF)",  "unit": "USD"},
        "XOP":   {"name": "XOP (Petrol & Gaz Arama)",   "unit": "USD"},
        "ICLN":  {"name": "ICLN (Temiz Enerji ETF)",    "unit": "USD"},
        "TAN":   {"name": "TAN (Güneş Enerjisi ETF)",    "unit": "USD"},
        "NLR":   {"name": "NLR (Nükleer Enerji ETF)",   "unit": "USD"},
        "XES":   {"name": "XES (Petrol Servisleri ETF)", "unit": "USD"},
        "OIH":   {"name": "OIH (Oil Services ETF)",      "unit": "USD"},
        "VDE":   {"name": "VDE (Vanguard Energy ETF)",   "unit": "USD"},
        "PXE":   {"name": "PXE (Dinamik Enerji ETF)",    "unit": "USD"},
        "CRAK":  {"name": "CRAK (Rafineri ETF)",         "unit": "USD"},
        "FCG":   {"name": "FCG (Doğalgaz Üreticileri)",  "unit": "USD"},
        "BNO":   {"name": "BNO (Brent Petrol Fonu)",     "unit": "USD"},
        "DBO":   {"name": "DBO (Petrol Fonu)",           "unit": "USD"},
        "UCO":   {"name": "UCO (Ham Petrol 2x)",         "unit": "USD"},
        "BOIL":  {"name": "BOIL (Doğalgaz 2x)",          "unit": "USD"},
    }
}

COMMODITIES_METALS = {
    "file": "commodities_metals.json",
    "category": "Kıymetli Madenler & Metaller",
    "symbols": {
        "GC=F":  {"name": "XAU (Altın)",      "unit": "USD/oz"},
        "SI=F":  {"name": "XAG (Gümüş)",      "unit": "USD/oz"},
        "PL=F":  {"name": "XPT (Platin)",      "unit": "USD/oz"},
        "PA=F":  {"name": "XPD (Paladyum)",    "unit": "USD/oz"},
        "HG=F":  {"name": "HG (Bakır)",       "unit": "USD/lb"},
        "ALI=F": {"name": "ALI (Alüminyum)",   "unit": "USD/ton"},
        "GLD":   {"name": "GLD (Altın ETF)",              "unit": "USD"},
        "SLV":   {"name": "SLV (Gümüş ETF)",              "unit": "USD"},
        "PPLT":  {"name": "PPLT (Platin ETF)",            "unit": "USD"},
        "PALL":  {"name": "PALL (Paladyum ETF)",          "unit": "USD"},
        "GDX":   {"name": "GDX (Altın Madencileri ETF)",   "unit": "USD"},
        "GDXJ":  {"name": "GDXJ (Küçük Altın Madencileri)", "unit": "USD"},
        "SIL":   {"name": "SIL (Gümüş Madencileri ETF)",   "unit": "USD"},
        # Fiziksel Maden Fonları (Kağıt üzerinde değil, kasasında gerçek maden tutan popüler fonlar)
        "PHYS":  {"name": "PHYS (Sprott Fiziksel Altın)", "unit": "USD"},
        "PSLV":  {"name": "PSLV (Sprott Fiziksel Gümüş)", "unit": "USD"},
        "SPPP":  {"name": "SPPP (Sprott Fiziksel Platin & Paladyum)", "unit": "USD"},
        "SIVR":  {"name": "SIVR (Fiziksel Gümüş ETF)", "unit": "USD"},

        # Madencilik Alt Kırılımları ve Spesifik ETF'ler
        "SILJ":  {"name": "SILJ (Küçük Gümüş Madencileri ETF)", "unit": "USD"},
        "RING":  {"name": "RING (Küresel Altın Madencileri)", "unit": "USD"},
        "PICK":  {"name": "PICK (Küresel Maden & Metal Üreticileri)", "unit": "USD"},
        "URNM":  {"name": "URNM (Uranyum Madencileri ETF)", "unit": "USD"}, # Nükleer trendi için çok popüler

        # Endüstriyel / Baz Metal ETF'leri (Vadeli kontratlar yerine fiyatı fon üzerinden takip etmek için)
        "CPER":  {"name": "CPER (Bakır ETF)", "unit": "USD"},
        "DBB":   {"name": "DBB (Baz Metaller Fonu - Al, Zn, Cu)", "unit": "USD"},
        "URA":   {"name": "URA (Uranyum ETF)", "unit": "USD"},
        "IAU":   {"name": "IAU (Altın ETF)", "unit": "USD"},
        "SGOL":  {"name": "SGOL (Fiziksel Altın ETF)", "unit": "USD"},
        "BAR":   {"name": "BAR (GraniteShares Gold)", "unit": "USD"},
        "DBP":   {"name": "DBP (Kıymetli Metaller Fonu)", "unit": "USD"},
        "JJN":   {"name": "JJN (Nikel ETN)", "unit": "USD"},
        "JJT":   {"name": "JJT (Kalay ETN)", "unit": "USD"},
    }
}

COMMODITIES_AGRICULTURE = {
    "file": "commodities_agriculture.json",
    "category": "Tarım",
    "symbols": {
        "ZW=F":  {"name": "ZW (Buğday)",       "unit": "USc/bu"},
        "ZC=F":  {"name": "ZC (Mısır)",        "unit": "USc/bu"},
        "ZS=F":  {"name": "ZS (Soya)","unit": "USc/bu"},
        "ZM=F":  {"name": "ZM (Soya Küspesi)",  "unit": "USD/ton"},
        "ZL=F":  {"name": "ZL (Soya Yağı)",    "unit": "USc/lb"},
        "ZO=F":  {"name": "ZO (Yulaf)",         "unit": "USc/bu"},
        "ZR=F":  {"name": "ZR (Pirinç)",        "unit": "USD/cwt"},
        "CT=F":  {"name": "CT (Pamuk)",         "unit": "USc/lb"},
        "KC=F":  {"name": "KC (Kahve)",         "unit": "USc/lb"},
        "SB=F":  {"name": "SB (Şeker)",         "unit": "USc/lb"},
        "CC=F":  {"name": "CC (Kakao)",         "unit": "USD/ton"},
        "OJ=F":  {"name": "OJ (Portakal Suyu)", "unit": "USc/lb"},
        "LBR=F": {"name": "LBR (Kereste)",       "unit": "USD/mbf"},
        "DBA":   {"name": "DBA (Tarım ETF)",      "unit": "USD"},
        "CORN":  {"name": "CORN (Mısır ETF)",     "unit": "USD"},
        "WEAT":  {"name": "WEAT (Buğday ETF)",    "unit": "USD"},
        "SOYB":  {"name": "SOYB (Soya ETF)",      "unit": "USD"},
        "MOO":   {"name": "MOO (Tarım Şirketleri ETF)", "unit": "USD"},
        "CANE":  {"name": "CANE (Şeker ETF)",     "unit": "USD"},
        "NIB":   {"name": "NIB (Kakao ETN)",      "unit": "USD"},
        "JO":    {"name": "JO (Kahve ETN)",       "unit": "USD"},
        "COW":   {"name": "COW (Hayvancılık ETN)", "unit": "USD"},
        "RJA":   {"name": "RJA (Tarım Endeksi ETN)", "unit": "USD"},
        "FTGC":  {"name": "FTGC (Çeşitlendirilmiş Emtia)", "unit": "USD"},
        "PDBA":  {"name": "PDBA (Optimum Yield Agriculture)", "unit": "USD"},
    }
}

CURRENCIES = {
    "file": "currencies.json",
    "category": "Döviz Kurları",
    "symbols": {
        # TRY çaprazları
        "USDTRY=X": {"name": "USD/TRY", "unit": "TRY"},
        "EURTRY=X": {"name": "EUR/TRY", "unit": "TRY"},
        "GBPTRY=X": {"name": "GBP/TRY", "unit": "TRY"},
        "CHFTRY=X": {"name": "CHF/TRY", "unit": "TRY"},
        # Majors
        "EURUSD=X": {"name": "EUR/USD", "unit": "USD"},
        "GBPUSD=X": {"name": "GBP/USD", "unit": "USD"},
        "USDJPY=X": {"name": "USD/JPY", "unit": "JPY"},
        "USDCHF=X": {"name": "USD/CHF", "unit": "CHF"},
        "AUDUSD=X": {"name": "AUD/USD", "unit": "USD"},
        "USDCAD=X": {"name": "USD/CAD", "unit": "CAD"},
        "NZDUSD=X": {"name": "NZD/USD", "unit": "USD"},
        "USDCNY=X": {"name": "USD/CNY", "unit": "CNY"},
        # Gelişen piyasalar & diğer
        "USDBRL=X": {"name": "USD/BRL", "unit": "BRL"},
        "USDMXN=X": {"name": "USD/MXN", "unit": "MXN"},
        "USDINR=X": {"name": "USD/INR", "unit": "INR"},
        "USDZAR=X": {"name": "USD/ZAR", "unit": "ZAR"},
        "USDSEK=X": {"name": "USD/SEK", "unit": "SEK"},
        "USDNOK=X": {"name": "USD/NOK", "unit": "NOK"},
        "USDSGD=X": {"name": "USD/SGD", "unit": "SGD"},
        "USDTHB=X": {"name": "USD/THB", "unit": "THB"},
        "USDKRW=X": {"name": "USD/KRW", "unit": "KRW"},
        # Endeks
        "DX-Y.NYB": {"name": "Dolar Endeksi (DXY)", "unit": ""},
        # Avrupa ve Diğer Çaprazlar
        "EURGBP=X": {"name": "EUR/GBP", "unit": "GBP"},
        "EURCHF=X": {"name": "EUR/CHF", "unit": "CHF"},
        "GBPEUR=X": {"name": "GBP/EUR", "unit": "EUR"},
        # Gelişen Avrupa / Diğer
        "USDPLN=X": {"name": "USD/PLN (Polonya Zlotisi)", "unit": "PLN"},
        "USDHUF=X": {"name": "USD/HUF (Macar Forinti)", "unit": "HUF"},
        "USDAED=X": {"name": "USD/AED (BAE Dirhemi)", "unit": "AED"},
        "USDHKD=X": {"name": "USD/HKD", "unit": "HKD"},
        "USDIDR=X": {"name": "USD/IDR", "unit": "IDR"},
        "USDPHP=X": {"name": "USD/PHP", "unit": "PHP"},
        "USDILS=X": {"name": "USD/ILS", "unit": "ILS"},
        "USDCLP=X": {"name": "USD/CLP", "unit": "CLP"},
        "USDCOP=X": {"name": "USD/COP", "unit": "COP"},
        "USDKZT=X": {"name": "USD/KZT", "unit": "KZT"},
        "USDQAR=X": {"name": "USD/QAR", "unit": "QAR"},
        "EURJPY=X": {"name": "EUR/JPY", "unit": "JPY"},
        "GBPJPY=X": {"name": "GBP/JPY", "unit": "JPY"},
        "EURAUD=X": {"name": "EUR/AUD", "unit": "AUD"},
        "EURNOK=X": {"name": "EUR/NOK", "unit": "NOK"},
        "AUDJPY=X": {"name": "AUD/JPY", "unit": "JPY"},
        "CADJPY=X": {"name": "CAD/JPY", "unit": "JPY"},
        "CHFJPY=X": {"name": "CHF/JPY", "unit": "JPY"},
        "EURCAD=X": {"name": "EUR/CAD", "unit": "CAD"},
        "EURSEK=X": {"name": "EUR/SEK", "unit": "SEK"},
        "EURPLN=X": {"name": "EUR/PLN", "unit": "PLN"},
        "GBPCHF=X": {"name": "GBP/CHF", "unit": "CHF"},
        "GBPAUD=X": {"name": "GBP/AUD", "unit": "AUD"},
        "AUDCAD=X": {"name": "AUD/CAD", "unit": "CAD"},
        "AUDCHF=X": {"name": "AUD/CHF", "unit": "CHF"},
        "AUDNZD=X": {"name": "AUD/NZD", "unit": "NZD"},
        "CADCHF=X": {"name": "CAD/CHF", "unit": "CHF"},
        "CADSGD=X": {"name": "CAD/SGD", "unit": "SGD"},
        "CHFSGD=X": {"name": "CHF/SGD", "unit": "SGD"},
        "EURDKK=X": {"name": "EUR/DKK", "unit": "DKK"},
        "EURHUF=X": {"name": "EUR/HUF", "unit": "HUF"},
        "EURCZK=X": {"name": "EUR/CZK", "unit": "CZK"},
        "EURNZD=X": {"name": "EUR/NZD", "unit": "NZD"},
        "GBPCAD=X": {"name": "GBP/CAD", "unit": "CAD"},
        "GBPSEK=X": {"name": "GBP/SEK", "unit": "SEK"},
    }
}

BONDS = {
    "file": "bonds.json",
    "category": "Tahvil Faizleri",
    "symbols": {
        # ABD Hazine getirileri
        "^IRX":     {"name": "ABD 3 Aylık",       "unit": "%"},
        "2YY=F":    {"name": "ABD 2 Yıllık",       "unit": "%"},
        "^FVX":     {"name": "ABD 5 Yıllık",       "unit": "%"},
        "^TNX":     {"name": "ABD 10 Yıllık",      "unit": "%"},
        "^TYX":     {"name": "ABD 30 Yıllık",      "unit": "%"},
        # Tahvil ETF'leri
        "TLT":      {"name": "TLT (20+ Yıl Tahvil ETF)", "unit": "USD"},
        "IEF":      {"name": "IEF (7-10 Yıl Tahvil ETF)", "unit": "USD"},
        "SHY":      {"name": "SHY (1-3 Yıl Tahvil ETF)", "unit": "USD"},
        "TBT":      {"name": "TBT (Kısa Tahvil 2x Ters)", "unit": "USD"},
        "HYG":      {"name": "HYG (Yüksek Getirili Tahvil)", "unit": "USD"},
        "LQD":      {"name": "LQD (Yatırım Düzeyi Tahvil)", "unit": "USD"},
        "EMB":      {"name": "EMB (Gelişen Piyasa Tahvil)", "unit": "USD"},
        "BNDX":     {"name": "BNDX (Uluslararası Tahvil)", "unit": "USD"},
        "BND":      {"name": "BND (Toplam Tahvil Piyasası)", "unit": "USD"},
        "AGG":      {"name": "AGG (Core US Aggregate)", "unit": "USD"},
        "TIP":      {"name": "TIP (Enflasyona Endeksli Tahvil)", "unit": "USD"},
        "MUB":      {"name": "MUB (Belediye Tahvilleri)", "unit": "USD"},
        "JNK":      {"name": "JNK (High Yield ETF)", "unit": "USD"},
        "BIL":      {"name": "BIL (1-3 Ay Hazine Bonosu)", "unit": "USD"},
        "SGOV":     {"name": "SGOV (0-3 Ay Hazine)", "unit": "USD"},
        "VGIT":     {"name": "VGIT (Orta Vadeli Hazine)", "unit": "USD"},
        "EDV":      {"name": "EDV (Uzun Vadeli Treasury)", "unit": "USD"},
        "TIPS":     {"name": "PIMCO 15+ Year TIPS", "unit": "USD"},
        "BSV":      {"name": "BSV (Kısa Vadeli Toplam Tahvil)", "unit": "USD"},
        "SPSB":     {"name": "SPSB (Kısa Vadeli Şirket Tahvili)", "unit": "USD"},
        "VCSH":     {"name": "VCSH (Kısa Vadeli Kurumsal Tahvil)", "unit": "USD"},
        "VCIT":     {"name": "VCIT (Orta Vadeli Kurumsal Tahvil)", "unit": "USD"},
        "SHV":      {"name": "SHV (1-12 Ay Hazine Bonosu)", "unit": "USD"},
        "GOVT":     {"name": "GOVT (ABD Hazine Tahvilleri)", "unit": "USD"},
        "TLH":      {"name": "TLH (10-20 Yıl Hazine Tahvili)", "unit": "USD"},
        "SPTL":     {"name": "SPTL (Uzun Vadeli Hazine Tahvili)", "unit": "USD"},
        "BNDW":     {"name": "BNDW (Global Toplam Tahvil ETF)", "unit": "USD"},
        "SCHZ":     {"name": "SCHZ (US Aggregate Bond ETF)", "unit": "USD"},
        "SCHR":     {"name": "SCHR (Orta Vadeli US Treasury)", "unit": "USD"},
        "IGSB":     {"name": "IGSB (Kısa Vadeli Kurumsal Tahvil)", "unit": "USD"},
        "IGIB":     {"name": "IGIB (Orta Vadeli Kurumsal Tahvil)", "unit": "USD"},
        "USIG":     {"name": "USIG (iShares Broad USD Investment Grade)", "unit": "USD"},
        "MBB":      {"name": "MBB (Mortgage-Backed Securities ETF)", "unit": "USD"},
        "VMBS":     {"name": "VMBS (Vanguard Mortgage-Backed Securities)", "unit": "USD"},
        "HYLB":     {"name": "HYLB (High Yield Corporate Bond ETF)", "unit": "USD"},
        "FLOT":     {"name": "FLOT (Floating Rate Bond ETF)", "unit": "USD"},
        "TFLO":     {"name": "TFLO (Treasury Floating Rate Bond ETF)", "unit": "USD"},
        "GSY":      {"name": "GSY (Ultra Short Duration Bond ETF)", "unit": "USD"},
    }
}

INDICES = {
    "file": "indices.json",
    "category": "Endeksler",
    "symbols": {
        "XU100.IS":  {"name": "BIST 100",       "unit": "TRY"},
        "XU030.IS":  {"name": "BIST 30",        "unit": "TRY"},
        "^GSPC":     {"name": "S&P 500",        "unit": "USD"},
        "^DJI":      {"name": "Dow Jones",      "unit": "USD"},
        "^IXIC":     {"name": "NASDAQ",         "unit": "USD"},
        "^RUT":      {"name": "Russell 2000",   "unit": "USD"},
        "^STOXX50E": {"name": "Euro Stoxx 50",  "unit": "EUR"},
        "^FTSE":     {"name": "FTSE 100",       "unit": "GBP"},
        "^GDAXI":    {"name": "DAX 40",         "unit": "EUR"},
        "^FCHI":     {"name": "CAC 40",         "unit": "EUR"},
        "^N225":     {"name": "Nikkei 225",     "unit": "JPY"},
        "^HSI":      {"name": "Hang Seng",      "unit": "HKD"},
        "000001.SS": {"name": "Shanghai Comp.",  "unit": "CNY"},
        "^BSESN":    {"name": "BSE Sensex",     "unit": "INR"},
        "^KS11":     {"name": "KOSPI",          "unit": "KRW"},
        "^TWII":     {"name": "TAIEX",          "unit": "TWD"},
        "^MERV":     {"name": "MERVAL",         "unit": "ARS"},
        "^AXJO":     {"name": "ASX 200",        "unit": "AUD"},
        "^IBEX":     {"name": "IBEX 35",        "unit": "EUR"},
        "^VIX":     {"name": "VIX (Korku Endeksi)",     "unit": "Puan"},
        "^BVSP":     {"name": "Bovespa",        "unit": "BRL"},
        "^NSEI":     {"name": "Nifty 50",       "unit": "INR"},
        "^JKSE":     {"name": "IDX Composite",  "unit": "IDR"},
        "^TA125.TA": {"name": "TA-125",         "unit": "ILS"},
        "^AEX":      {"name": "AEX",            "unit": "EUR"},
        "^SSMI":     {"name": "SMI",            "unit": "CHF"},
        "^OMX":      {"name": "OMX Stockholm 30", "unit": "SEK"},
        "^N100":     {"name": "Euronext 100",   "unit": "EUR"},
        "^GSPTSE":   {"name": "S&P/TSX Composite", "unit": "CAD"},
        "^KLSE":     {"name": "FTSE Bursa Malaysia", "unit": "MYR"},
        "^NDX":      {"name": "NASDAQ 100", "unit": "USD"},
        "^MID":      {"name": "S&P MidCap 400", "unit": "USD"},
        "^SP600":    {"name": "S&P SmallCap 600", "unit": "USD"},
        "^NYA":      {"name": "NYSE Composite", "unit": "USD"},
        "^STI":      {"name": "Straits Times", "unit": "SGD"},
        "^MXX":      {"name": "IPC Mexico", "unit": "MXN"},
        "^AORD":     {"name": "All Ordinaries (Avustralya)", "unit": "AUD"},
        "^NZ50":     {"name": "S&P/NZX 50", "unit": "NZD"},
        "^FTMC":     {"name": "FTSE 250", "unit": "GBP"},
        "^BFX":      {"name": "BEL 20", "unit": "EUR"},
        "^ATX":      {"name": "Austrian Traded Index", "unit": "EUR"},
        "^PSI20":    {"name": "PSI 20 (Portekiz)", "unit": "EUR"},
        "^CASE30":   {"name": "EGX30 (Mısır)", "unit": "EGP"},
        "^JN0U.JO":  {"name": "Top 40 (Güney Afrika)", "unit": "ZAR"},
        "^TA35":     {"name": "TA-35 (İsrail)", "unit": "ILS"},
        "^N225M":    {"name": "Nikkei 225 Futures Mini", "unit": "JPY"},
        "^SET.BK":   {"name": "SET Index (Tayland)", "unit": "THB"},
        "^SSEC":     {"name": "Shanghai Composite (SSEC)", "unit": "CNY"},
    }
}

CRYPTO = {
    "file": "crypto.json",
    "category": "Kripto Paralar",
    "symbols": {
        "BTC-USD":  {"name": "BTC (Bitcoin)",    "unit": "USD"},
        "ETH-USD":  {"name": "ETH (Ethereum)",   "unit": "USD"},
        "BNB-USD":  {"name": "BNB",              "unit": "USD"},
        "SOL-USD":  {"name": "SOL (Solana)",     "unit": "USD"},
        "XRP-USD":  {"name": "XRP",              "unit": "USD"},
        "ADA-USD":  {"name": "ADA (Cardano)",    "unit": "USD"},
        "DOGE-USD": {"name": "DOGE (Dogecoin)",  "unit": "USD"},
        "AVAX-USD": {"name": "AVAX (Avalanche)", "unit": "USD"},
        "DOT-USD":  {"name": "DOT (Polkadot)",   "unit": "USD"},
        "LINK-USD": {"name": "LINK (Chainlink)", "unit": "USD"},
        "POL-USD": {"name": "POL (Polygon)",     "unit": "USD"},
        "TRX-USD":  {"name": "TRX (Tron)",       "unit": "USD"},
        "BCH-USD":  {"name": "BCH (Bitcoin Cash)","unit": "USD"},
        "LTC-USD":  {"name": "LTC (Litecoin)",   "unit": "USD"},
        "UNI7083-USD": {"name": "UNI (Uniswap)", "unit": "USD"},
        "ATOM-USD": {"name": "ATOM (Cosmos)",     "unit": "USD"},
        "NEAR-USD": {"name": "NEAR Protocol",    "unit": "USD"},
        "APT-USD":  {"name": "APT (Aptos)",       "unit": "USD"},
        "SUI20947-USD": {"name": "SUI",           "unit": "USD"},
        "TON11419-USD": {"name": "TON (Toncoin)", "unit": "USD"},
        "HBAR-USD": {"name": "HBAR (Hedera)", "unit": "USD"},
        "XLM-USD": {"name": "XLM (Stellar)", "unit": "USD"},
        "ETC-USD": {"name": "ETC (Ethereum Classic)", "unit": "USD"},
        "FIL-USD": {"name": "FIL (Filecoin)", "unit": "USD"},
        "ARB11841-USD": {"name": "ARB (Arbitrum)", "unit": "USD"},
        "OP-USD": {"name": "OP (Optimism)", "unit": "USD"},
        "SEI-USD": {"name": "SEI", "unit": "USD"},
        "INJ-USD": {"name": "INJ (Injective)", "unit": "USD"},
        "RUNE-USD": {"name": "RUNE (THORChain)", "unit": "USD"},
        "WIF-USD": {"name": "WIF (dogwifhat)", "unit": "USD"},
    }
}

INDUSTRIAL = {
    "file": "industrial.json",
    "category": "Sanayi & Hammadde",
    "symbols": {
        "HG=F":   {"name": "HG (Bakır)",         "unit": "USD/lb"},
        "ALI=F":  {"name": "ALI (Alüminyum)",     "unit": "USD/ton"},
        "ZN=F":   {"name": "ZN (Çinko)",          "unit": "USD/ton"},
        "LBR=F":  {"name": "LBR (Kereste)",        "unit": "USD/mbf"},
        "URA":    {"name": "URA (Uranyum ETF)",    "unit": "USD"},
        "LIT":    {"name": "LIT (Lityum ETF)",     "unit": "USD"},
        "COPX":   {"name": "COPX (Bakır Madenci)", "unit": "USD"},
        "SLX":    {"name": "SLX (Çelik ETF)",      "unit": "USD"},
        "BDRY":   {"name": "BDRY (Kuru Yük Navlun)","unit": "USD"},
        "REMX":   {"name": "REMX (Nadir Toprak)",  "unit": "USD"},
        # Temel Materyaller ve Geniş Sanayi Fonları
        "XLB":    {"name": "XLB (Temel Materyaller ETF)", "unit": "USD"}, # Kimya, ambalaj, inşaat malzemeleri
        "XLI":    {"name": "XLI (Sanayi Sektörü ETF)", "unit": "USD"},    # Ağır sanayi, makine ve havacılık
        "GUNR":   {"name": "GUNR (Küresel Doğal Kaynaklar)", "unit": "USD"},
        
        # Geleceğin Hammaddeleri ve Batarya Teknolojileri (LIT'i tamamlayıcı)
        "BATT":   {"name": "BATT (Batarya Teknolojileri ETF)", "unit": "USD"},
        
        # Altyapı, İnşaat ve Diğer Kaynaklar
        "PAVE":   {"name": "PAVE (Altyapı ve İnşaat ETF)", "unit": "USD"},
        "WOOD":   {"name": "WOOD (Küresel Kereste ve Ormancılık)", "unit": "USD"}, # LBS=F (Kereste) fon karşılığı
        "FIW":    {"name": "FIW (Su Kaynakları ETF)", "unit": "USD"}, # Sanayinin en büyük sarf kalemi
        
        # Taşımacılık ve Lojistik (BDRY'yi tamamlayıcı)
        "IYT":    {"name": "IYT (Taşımacılık Sektörü ETF)", "unit": "USD"},
        "AIRR":   {"name": "AIRR (Industrial Renaissance ETF)", "unit": "USD"},
        "MXI":    {"name": "MXI (Global Materials ETF)", "unit": "USD"},
        "IGE":    {"name": "IGE (North American Natural Resources)", "unit": "USD"},
        "GNR":    {"name": "GNR (Global Natural Resources)", "unit": "USD"},
        "XME":    {"name": "XME (Metals & Mining ETF)", "unit": "USD"},
        "DOV":    {"name": "Dover", "unit": "USD"},
        "IR":     {"name": "Ingersoll Rand", "unit": "USD"},
        "PCAR":   {"name": "Paccar", "unit": "USD"},
        "WM":     {"name": "Waste Management", "unit": "USD"},
        "VIS":    {"name": "Vanguard Industrials ETF", "unit": "USD"},
        "IYJ":    {"name": "iShares U.S. Industrials ETF", "unit": "USD"},
        "FIDU":   {"name": "Fidelity MSCI Industrials ETF", "unit": "USD"},
        "ITA":    {"name": "iShares U.S. Aerospace & Defense ETF", "unit": "USD"},
        "PKB":    {"name": "Invesco Building & Construction ETF", "unit": "USD"},
        "PHO":    {"name": "Invesco Water Resources ETF", "unit": "USD"},
        "IFRA":   {"name": "iShares U.S. Infrastructure ETF", "unit": "USD"},
        "XAR":    {"name": "SPDR S&P Aerospace & Defense ETF", "unit": "USD"},
        "PPA":    {"name": "Invesco Aerospace & Defense ETF", "unit": "USD"},
        "XTN":    {"name": "SPDR S&P Transportation ETF", "unit": "USD"},
        "JETS":   {"name": "U.S. Global Jets ETF", "unit": "USD"},
        "SEA":    {"name": "U.S. Global Sea to Sky Cargo ETF", "unit": "USD"},
        "IPAY":   {"name": "ETFMG Prime Mobile Payments ETF", "unit": "USD"},
        "URAA":   {"name": "Deep Yellow Uranium & Nuclear ETF", "unit": "USD"},
        "COPJ":   {"name": "Sprott Junior Copper Miners ETF", "unit": "USD"},
        "LITP":   {"name": "Sprott Lithium Miners ETF", "unit": "USD"},
        "AIRS":   {"name": "First Trust RBA American Industrial Renaissance ETF", "unit": "USD"},
        "GRID":   {"name": "First Trust NASDAQ Clean Edge Smart Grid ETF", "unit": "USD"},
        "MLPX":   {"name": "Global X MLP & Energy Infrastructure ETF", "unit": "USD"},
    }
}

STOCKS = {
    "file": "stocks.json",
    "category": "Hisse Senetleri",
    "symbols": {
        # ═══════════════════════════════════════
        # BIST — Bankacılık
        # ═══════════════════════════════════════
        "GARAN.IS":  {"name": "Garanti BBVA",      "unit": "TRY"},
        "AKBNK.IS":  {"name": "Akbank",            "unit": "TRY"},
        "YKBNK.IS":  {"name": "Yapı Kredi",        "unit": "TRY"},
        "ISCTR.IS":  {"name": "İş Bankası C",      "unit": "TRY"},
        "VAKBN.IS":  {"name": "VakıfBank",         "unit": "TRY"},
        "HALKB.IS":  {"name": "Halkbank",          "unit": "TRY"},
        "TSKB.IS":   {"name": "TSKB",              "unit": "TRY"},
        "QNBFB.IS":  {"name": "QNB Finansbank",    "unit": "TRY"},
        "ALBRK.IS":  {"name": "Albaraka Türk",     "unit": "TRY"},
        "SKBNK.IS":  {"name": "Şekerbank",         "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — Holding & Yatırım
        # ═══════════════════════════════════════
        "KCHOL.IS":  {"name": "Koç Holding",       "unit": "TRY"},
        "SAHOL.IS":  {"name": "Sabancı Holding",   "unit": "TRY"},
        "DOHOL.IS":  {"name": "Doğan Holding",     "unit": "TRY"},
        "AGHOL.IS":  {"name": "AG Anadolu Grubu",  "unit": "TRY"},
        "TKFEN.IS":  {"name": "Tekfen Holding",    "unit": "TRY"},
        "TAVHL.IS":  {"name": "TAV Havalimanları",  "unit": "TRY"},
        "GSRAY.IS":  {"name": "Galatasaray",  "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — Sanayi & Üretim
        # ═══════════════════════════════════════
        "EREGL.IS":  {"name": "Ereğli Demir Çelik","unit": "TRY"},
        "TUPRS.IS":  {"name": "Tüpraş",           "unit": "TRY"},
        "ASELS.IS":  {"name": "ASELSAN",           "unit": "TRY"},
        "FROTO.IS":  {"name": "Ford Otosan",       "unit": "TRY"},
        "TOASO.IS":  {"name": "Tofaş Oto.",        "unit": "TRY"},
        "SISE.IS":   {"name": "Şişecam",           "unit": "TRY"},
        "ARCLK.IS":  {"name": "Arçelik",           "unit": "TRY"},
        "VESTL.IS":  {"name": "Vestel",            "unit": "TRY"},
        "OTKAR.IS":  {"name": "Otokar",            "unit": "TRY"},
        "KRDMD.IS":  {"name": "Kardemir D",        "unit": "TRY"},
        "TTRAK.IS":  {"name": "Türk Traktör",      "unit": "TRY"},
        "BRISA.IS":  {"name": "Brisa",             "unit": "TRY"},
        "PETKM.IS":  {"name": "Petkim",            "unit": "TRY"},
        "ENKAI.IS":  {"name": "Enka İnşaat",       "unit": "TRY"},
        "CIMSA.IS":  {"name": "Çimsa",             "unit": "TRY"},
        "OYAKC.IS":  {"name": "Oyak Çimento",      "unit": "TRY"},
        "SASA.IS":   {"name": "SASA Polyester",    "unit": "TRY"},
        "EGEEN.IS":  {"name": "Ege Endüstri",      "unit": "TRY"},
        "CEMTS.IS":  {"name": "Çemtaş Çelik",      "unit": "TRY"},
        "KLMSN.IS":  {"name": "Klimasan",          "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — Havacılık & Ulaşım
        # ═══════════════════════════════════════
        "THYAO.IS":  {"name": "THY",               "unit": "TRY"},
        "PGSUS.IS":  {"name": "Pegasus",           "unit": "TRY"},
        "DOAS.IS":   {"name": "Doğuş Otomotiv",    "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — Perakende & Tüketim
        # ═══════════════════════════════════════
        "BIMAS.IS":  {"name": "BİM Mağazaları",   "unit": "TRY"},
        "MGROS.IS":  {"name": "Migros",            "unit": "TRY"},
        "SOKM.IS":   {"name": "Şok Market",        "unit": "TRY"},
        "ULKER.IS":  {"name": "Ülker",             "unit": "TRY"},
        "AEFES.IS":  {"name": "Anadolu Efes",      "unit": "TRY"},
        "CCOLA.IS":  {"name": "Coca-Cola İçecek",  "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — Telekom & Teknoloji
        # ═══════════════════════════════════════
        "TCELL.IS":  {"name": "Turkcell",          "unit": "TRY"},
        "TTKOM.IS":  {"name": "Türk Telekom",      "unit": "TRY"},
        "LOGO.IS":   {"name": "Logo Yazılım",      "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — Enerji
        # ═══════════════════════════════════════
        "AKSEN.IS":  {"name": "Aksa Enerji",       "unit": "TRY"},
        "AKSA.IS":   {"name": "Aksa Akrilik",      "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — Madencilik & Tarım
        # ═══════════════════════════════════════
        "KOZAL.IS":  {"name": "Koza Altın",        "unit": "TRY"},
        "KOZAA.IS":  {"name": "Koza Anadolu Metal","unit": "TRY"},
        "GUBRF.IS":  {"name": "Gübre Fabrikaları", "unit": "TRY"},
        "HEKTS.IS":  {"name": "Hektaş",            "unit": "TRY"},
        # ═══════════════════════════════════════
        # BIST — GYO & Sigorta & Finans
        # ═══════════════════════════════════════
        "EKGYO.IS":  {"name": "Emlak Konut GYO",   "unit": "TRY"},
        "ISGYO.IS":  {"name": "İş GYO",            "unit": "TRY"},
        "TURSG.IS":  {"name": "Türkiye Sigorta",   "unit": "TRY"},
        "KONTR.IS":  {"name": "Kontrolmatik",      "unit": "TRY"},
        "ASTOR.IS":  {"name": "Astor Enerji",      "unit": "TRY"},
        "SMRTG.IS":  {"name": "Smart Güneş",       "unit": "TRY"},
        "CWENE.IS":  {"name": "CW Enerji",         "unit": "TRY"},
        "GESAN.IS":  {"name": "Girişim Elektrik",  "unit": "TRY"},
        "ODAS.IS":   {"name": "Odaş Elektrik",     "unit": "TRY"},
        "ZOREN.IS":  {"name": "Zorlu Enerji",      "unit": "TRY"},
        "ENJSA.IS":  {"name": "Enerjisa Enerji",   "unit": "TRY"},
        "ALFAS.IS":  {"name": "Alfa Solar",        "unit": "TRY"},
        "MIATK.IS":  {"name": "Mia Teknoloji",     "unit": "TRY"},
        "KCAER.IS":  {"name": "Kocaer Çelik",      "unit": "TRY"},
        "BORLS.IS":  {"name": "Borlease",          "unit": "TRY"},
        "REEDR.IS":  {"name": "Reeder Teknoloji",  "unit": "TRY"},
        "TABGD.IS":  {"name": "TAB Gıda",          "unit": "TRY"},
        "MAVI.IS":   {"name": "Mavi Giyim",        "unit": "TRY"},
        "KONYA.IS":  {"name": "Konya Çimento",     "unit": "TRY"},
        "SOKM.IS":   {"name": "Şok Market",        "unit": "TRY"},
        "MPARK.IS":  {"name": "MLP Sağlık",        "unit": "TRY"},
        "GENIL.IS":  {"name": "Gen İlaç",          "unit": "TRY"},
        "ECILC.IS":  {"name": "Eczacıbaşı İlaç",   "unit": "TRY"},
        "SELEC.IS":  {"name": "Selçuk Ecza",       "unit": "TRY"},
        "FENER.IS":  {"name": "Fenerbahçe",        "unit": "TRY"},
        "BJKAS.IS":  {"name": "Beşiktaş",          "unit": "TRY"},
        "TRGYO.IS":  {"name": "Torunlar GYO",      "unit": "TRY"},
        "AKFGY.IS":  {"name": "Akfen GYO",         "unit": "TRY"},
        "VAKKO.IS":  {"name": "Vakko",             "unit": "TRY"},
        "PRKME.IS":  {"name": "Park Elektrik",     "unit": "TRY"},
        "DOHOL.IS":  {"name": "Doğan Holding",     "unit": "TRY"},
        "ENERY.IS":  {"name": "Enerya Enerji",     "unit": "TRY"},
        "EUPWR.IS":  {"name": "Europower Enerji",  "unit": "TRY"},

        # ── BIST Tam Liste (Ek) ─────────────────────
        "A1CAP.IS": {"name": "A1 Capital Yatırım Menkul Değerler", "unit": "TRY"},
        "A1YEN.IS": {"name": "A1 Yenilenebilir Enerji", "unit": "TRY"},
        "ACSEL.IS": {"name": "Acıselsan", "unit": "TRY"},
        "ADEL.IS": {"name": "Adel Kalemcilik", "unit": "TRY"},
        "ADESE.IS": {"name": "Adese Gayrimenkul", "unit": "TRY"},
        "ADGYO.IS": {"name": "Adra GYO", "unit": "TRY"},
        "AFYON.IS": {"name": "Afyon Çimento", "unit": "TRY"},
        "AGROT.IS": {"name": "Agrotech Yüksek Teknoloji", "unit": "TRY"},
        "AGYO.IS": {"name": "Atakule GYO", "unit": "TRY"},
        "AHGAZ.IS": {"name": "Ahlatcı Doğalgaz", "unit": "TRY"},
        "AHSGY.IS": {"name": "Ahes Gayrimenkul", "unit": "TRY"},
        "AKENR.IS": {"name": "Akenerji", "unit": "TRY"},
        "AKSGY.IS": {"name": "Ak İş GYO", "unit": "TRY"},
        "AKSUE.IS": {"name": "Aksu Enerji" , "unit": "TRY"},
        "AKYHO.IS": {"name": "Akdeniz Yatırım", "unit": "TRY"},
        "ALCAR.IS": {"name": "Alarko Carrier", "unit": "TRY"},
        "ALCTL.IS": {"name": "Alcatel Lucent Teletaş", "unit": "TRY"},
        "ALGYO.IS": {"name": "Alarko GYO", "unit": "TRY"},
        "ALKA.IS": {"name": "Alkim Kağıt", "unit": "TRY"},
        "ALKIM.IS": {"name": "Alkim Alkali Kimya", "unit": "TRY"},
        "ANELE.IS": {"name": "Anel Elektrik", "unit": "TRY"},
        "ANGEN.IS": {"name": "Anatolia Tanı Teknolojileri", "unit": "TRY"},
        "ARDYZ.IS": {"name": "ARD Bilişim Teknolojileri", "unit": "TRY"},
        "ARENA.IS": {"name": "Arena Bilgisayar", "unit": "TRY"},
        "ARSAN.IS": {"name": "Arsan Tekstil", "unit": "TRY"},
        "ASGYO.IS": {"name": "Asce GYO", "unit": "TRY"},
        "ASUZU.IS": {"name": "Anadolu Isuzu", "unit": "TRY"},
        "ATAGY.IS": {"name": "Ata GYO", "unit": "TRY"},
        "ATAKP.IS": {"name": "Atakey Patates", "unit": "TRY"},
        "ATATP.IS": {"name": "ATP Yazılım", "unit": "TRY"},
        "ATEKS.IS": {"name": "Akın Tekstil", "unit": "TRY"},
        "ATLAS.IS": {"name": "Atlas Menkul Kıymetler", "unit": "TRY"},
        "ATSYH.IS": {"name": "Atlantis Yatırım Holding", "unit": "TRY"},
        "AVGYO.IS": {"name": "Avrasya GYO", "unit": "TRY"},
        "AVHOL.IS": {"name": "Avrupa Yatırım Holding", "unit": "TRY"},
        "AVOD.IS": {"name": "A.V.O.D. Gıda", "unit": "TRY"},
        "AVPGY.IS": {"name": "Avrupakent GYO", "unit": "TRY"},
        "AVTUR.IS": {"name": "Avrasya Turizm", "unit": "TRY"},
        "AYCES.IS": {"name": "Altınyunus Çeşme", "unit": "TRY"},
        "AYDEM.IS": {"name": "Aydem Yenilenebilir Enerji", "unit": "TRY"},
        "AYEN.IS": {"name": "Ayen Enerji", "unit": "TRY"},
        "AYES.IS": {"name": "Ayes Çelik Hasır", "unit": "TRY"},
        "AYGAZ.IS": {"name": "Aygaz", "unit": "TRY"},
        "AZTEK.IS": {"name": "Aztek Teknoloji", "unit": "TRY"},
        "BAGFS.IS": {"name": "Bagfaş", "unit": "TRY"},
        "BAHKM.IS": {"name": "Bahadır Kimya", "unit": "TRY"},
        "BAKAB.IS": {"name": "Bak Ambalaj", "unit": "TRY"},
        "BALAT.IS": {"name": "Balatacılar Balatacılık", "unit": "TRY"},
        "BARMA.IS": {"name": "Barem Ambalaj", "unit": "TRY"},
        "BASCM.IS": {"name": "Baştaş Çimento", "unit": "TRY"},
        "BASGZ.IS": {"name": "Başkent Doğalgaz", "unit": "TRY"},
        "BAYRK.IS": {"name": "Bayrak EBT Taban", "unit": "TRY"},
        "BEGYO.IS": {"name": "Batı Ege GYO", "unit": "TRY"},
        "BERA.IS": {"name": "Bera Holding", "unit": "TRY"},
        "BESLR.IS": {"name": "Besler Gıda", "unit": "TRY"},
        "BEYAZ.IS": {"name": "Beyaz Filo", "unit": "TRY"},
        "BFREN.IS": {"name": "Bosch Fren Sistemleri", "unit": "TRY"},
        "BIENY.IS": {"name": "Bien Yapı Ürünleri", "unit": "TRY"},
        "BINHO.IS": {"name": "1000 Yatırımlar Holding", "unit": "TRY"},
        "BIZIM.IS": {"name": "Bizim Toptan", "unit": "TRY"},
        "BLCYT.IS": {"name": "Bilici Yatırım", "unit": "TRY"},
        "BMSCH.IS": {"name": "BMS Çelik Hasır", "unit": "TRY"},
        "BMSTL.IS": {"name": "BMS Birleşik Metal", "unit": "TRY"},
        "BNTAS.IS": {"name": "Bantaş Ambalaj", "unit": "TRY"},
        "BOSSA.IS": {"name": "Bossa Ticaret", "unit": "TRY"},
        "BRKO.IS": {"name": "Birko Mensucat", "unit": "TRY"},
        "BRKSN.IS": {"name": "Berkosan Yalıtım", "unit": "TRY"},
        "BRLSM.IS": {"name": "Birleşim Mühendislik", "unit": "TRY"},
        "BRMEN.IS": {"name": "Birlik Mensucat", "unit": "TRY"},
        "BRSAN.IS": {"name": "Borusan Boru", "unit": "TRY"},
        "BRYAT.IS": {"name": "Borusan Yatırım", "unit": "TRY"},
        "BSOKE.IS": {"name": "Batısöke Çimento", "unit": "TRY"},
        "BTCIM.IS": {"name": "Batı Çimento", "unit": "TRY"},
        "BUCIM.IS": {"name": "Bursa Çimento", "unit": "TRY"},
        "BURCE.IS": {"name": "Burçelik", "unit": "TRY"},
        "BURVA.IS": {"name": "Burçelik Vana", "unit": "TRY"},
        "BVSAN.IS": {"name": "Bülbüloğlu Vinç", "unit": "TRY"},
        "BYDNR.IS": {"name": "Baydöner", "unit": "TRY"},
        "CANTE.IS": {"name": "Çan2 Termik", "unit": "TRY"},
        "CASA.IS": {"name": "Casa Emtia", "unit": "TRY"},
        "CELHA.IS": {"name": "Çelik Halat", "unit": "TRY"},
        "CEMAS.IS": {"name": "Çemaş Döküm", "unit": "TRY"},
        "CEOEM.IS": {"name": "CEO Event Medya", "unit": "TRY"},
        "CLEBI.IS": {"name": "Çelebi Hava Servisi", "unit": "TRY"},
        "CMBTN.IS": {"name": "Çimbeton", "unit": "TRY"},
        "CMENT.IS": {"name": "Çimentaş", "unit": "TRY"},
        "CONSE.IS": {"name": "Consus Enerji", "unit": "TRY"},
        "COSMO.IS": {"name": "Cosmos Yatırım Holding", "unit": "TRY"},
        "CRDFA.IS": {"name": "Creditwest Faktoring", "unit": "TRY"},
        "CRFSA.IS": {"name": "Carrefoursa", "unit": "TRY"},
        "CUSAN.IS": {"name": "Çuhadaroğlu Metal", "unit": "TRY"},
        "CVKMD.IS": {"name": "CVK Maden", "unit": "TRY"},
        "DAGHL.IS": {"name": "Dagi Yatırım Holding", "unit": "TRY"},
        "DAGI.IS": {"name": "Dagi Giyim", "unit": "TRY"},
        "DARDL.IS": {"name": "Dardanel", "unit": "TRY"},
        "DENGE.IS": {"name": "Denge Yatırım Holding", "unit": "TRY"},
        "DERHL.IS": {"name": "Derlüks Yatırım Holding", "unit": "TRY"},
        "DERIM.IS": {"name": "Derimod", "unit": "TRY"},
        "DESA.IS": {"name": "Desa Deri", "unit": "TRY"},
        "DEVA.IS": {"name": "Deva Holding", "unit": "TRY"},
        "DGATE.IS": {"name": "Datagate Bilgisayar", "unit": "TRY"},
        "DGGYO.IS": {"name": "Doğuş GYO", "unit": "TRY"},
        "DGNMO.IS": {"name": "Doğanlar Mobilya", "unit": "TRY"},
        "DIRIT.IS": {"name": "Diriteks Diriliş Tekstil", "unit": "TRY"},
        "DITAS.IS": {"name": "Ditaş Doğan Yedek Parça", "unit": "TRY"},
        "DOBUR.IS": {"name": "Doğan Burda", "unit": "TRY"},
        "DOGUB.IS": {"name": "Doğusan Boru", "unit": "TRY"},
        "DOKTA.IS": {"name": "Döktaş", "unit": "TRY"},
        "DURDO.IS": {"name": "Duran Doğan Basım", "unit": "TRY"},
        "DYOBY.IS": {"name": "Dyo Boya", "unit": "TRY"},
        "EBEBK.IS": {"name": "Ebebek", "unit": "TRY"},
        "ECZYT.IS": {"name": "Eczacıbaşı Yatırım", "unit": "TRY"},
        "EDATA.IS": {"name": "E-Data Teknoloji", "unit": "TRY"},
        "EDIP.IS": {"name": "Edip Gayrimenkul", "unit": "TRY"},
        "EGEPO.IS": {"name": "Nasmed Egepol", "unit": "TRY"},
        "EGGUB.IS": {"name": "Ege Gübre", "unit": "TRY"},
        "EGPRO.IS": {"name": "Ege Profil", "unit": "TRY"},
        "EGSER.IS": {"name": "Ege Seramik", "unit": "TRY"},
        "EKIZ.IS": {"name": "Ekiz Kimya", "unit": "TRY"},
        "EKSUN.IS": {"name": "Eksun Gıda", "unit": "TRY"},
        "ELITE.IS": {"name": "Elite Naturel", "unit": "TRY"},
        "EMKEL.IS": {"name": "Emek Elektrik", "unit": "TRY"},
        "EMNIS.IS": {"name": "Eminiş Ambalaj", "unit": "TRY"},
        "EPLAS.IS": {"name": "Egeplast", "unit": "TRY"},
        "ERBOS.IS": {"name": "Erbosan", "unit": "TRY"},
        "ERCB.IS": {"name": "Erciyas Çelik Boru", "unit": "TRY"},
        "ERSU.IS": {"name": "Ersu Gıda", "unit": "TRY"},
        "ESCAR.IS": {"name": "Escar Filo", "unit": "TRY"},
        "ESCOM.IS": {"name": "Escort Teknoloji", "unit": "TRY"},
        "ESEN.IS": {"name": "Esenboğa Elektrik", "unit": "TRY"},
        "ETILR.IS": {"name": "Etiler Gıda", "unit": "TRY"},
        "ETYAT.IS": {"name": "Euro Trend Yatırım Ortaklığı", "unit": "TRY"},
        "EUHOL.IS": {"name": "Euro Yatırım Holding", "unit": "TRY"},
        "EUKYO.IS": {"name": "Euro Kapital Yatırım Ortaklığı", "unit": "TRY"},
        "EUREN.IS": {"name": "Europen Endüstri", "unit": "TRY"},
        "EYGYO.IS": {"name": "EYG GYO", "unit": "TRY"},
        "FADE.IS": {"name": "Fade Gıda", "unit": "TRY"},
        "FLAP.IS": {"name": "Flap Kongre Toplantı", "unit": "TRY"},
        "FMIZP.IS": {"name": "Federal-Mogul İzmit Piston", "unit": "TRY"},
        "FONET.IS": {"name": "Fonet Bilgi Teknolojileri", "unit": "TRY"},
        "FORMT.IS": {"name": "Formet Metal ve Cam", "unit": "TRY"},
        "FORTE.IS": {"name": "Forte Bilgi İletişim", "unit": "TRY"},
        "FRIGO.IS": {"name": "Frigo-Pak Gıda", "unit": "TRY"},
        "FZLGY.IS": {"name": "Fuzul GYO", "unit": "TRY"},
        "GARFA.IS": {"name": "Garanti Faktoring", "unit": "TRY"},
        "GEDIK.IS": {"name": "Gedik Yatırım", "unit": "TRY"},
        "GEDZA.IS": {"name": "Gediz Ambalaj", "unit": "TRY"},
        "GENTS.IS": {"name": "Gentaş", "unit": "TRY"},
        "GEREL.IS": {"name": "Gersan Elektrik", "unit": "TRY"},
        "GIPTA.IS": {"name": "Gıpta Ofis", "unit": "TRY"},
        "GLCVY.IS": {"name": "Gelecek Varlık Yönetimi", "unit": "TRY"},
        "GLRYH.IS": {"name": "Güler Yatırım Holding", "unit": "TRY"},
        "GMTAS.IS": {"name": "Gimat Mağazacılık", "unit": "TRY"},
        "GOKNR.IS": {"name": "Göknur Gıda", "unit": "TRY"},
        "GOODY.IS": {"name": "Goodyear", "unit": "TRY"},
        "GRNYO.IS": {"name": "Garanti Yatırım Ortaklığı", "unit": "TRY"},
        "GRSEL.IS": {"name": "Gürsel Turizm", "unit": "TRY"},
        "GSDDE.IS": {"name": "GSD Denizcilik", "unit": "TRY"},
        "GZNMI.IS": {"name": "Gezinomi Seyahat", "unit": "TRY"},
        "HATEK.IS": {"name": "Hateks Hatay Tekstil", "unit": "TRY"},
        "HATSN.IS": {"name": "Hat-San Gemi", "unit": "TRY"},
        "HDFGS.IS": {"name": "Hedef Girişim", "unit": "TRY"},
        "HEDEF.IS": {"name": "Hedef Holding", "unit": "TRY"},
        "HKTM.IS": {"name": "Hidropar Hareket", "unit": "TRY"},
        "HLGYO.IS": {"name": "Halk GYO", "unit": "TRY"},
        "HTTBT.IS": {"name": "Hitit Bilgisayar", "unit": "TRY"},
        "HUBVC.IS": {"name": "Hub Girişim", "unit": "TRY"},
        "HUNER.IS": {"name": "Hun Yenilenebilir Enerji", "unit": "TRY"},
        "HURGZ.IS": {"name": "Hürriyet Gazetecilik", "unit": "TRY"},
        "ICBCT.IS": {"name": "ICBC Turkey Bank", "unit": "TRY"},
        "ICUGS.IS": {"name": "ICU Girişim", "unit": "TRY"},
        "IDEAS.IS": {"name": "İdeal Finansal Teknolojiler", "unit": "TRY"},
        "IDGYO.IS": {"name": "İdealist GYO", "unit": "TRY"},
        "IEYHO.IS": {"name": "Işıklar Enerji ve Yapı Holding", "unit": "TRY"},
        "IHAAS.IS": {"name": "İhlas Haber Ajansı", "unit": "TRY"},
        "IHEVA.IS": {"name": "İhlas Ev Aletleri", "unit": "TRY"},
        "IHGZT.IS": {"name": "İhlas Gazetecilik", "unit": "TRY"},
        "IHYAY.IS": {"name": "İhlas Yayın Holding", "unit": "TRY"},
        "IMASM.IS": {"name": "İmaş Makina", "unit": "TRY"},
        "INFO.IS": {"name": "Info Yatırım", "unit": "TRY"},
        "INGRM.IS": {"name": "İngram Micro Bilişim", "unit": "TRY"},
        "INTEM.IS": {"name": "İntema", "unit": "TRY"},
        "INVEO.IS": {"name": "Inveo Yatırım Holding", "unit": "TRY"},
        "INVES.IS": {"name": "Investco Holding", "unit": "TRY"},
        "IPEKE.IS": {"name": "İpek Doğal Enerji", "unit": "TRY"},
        "ISBIR.IS": {"name": "İşbir Holding", "unit": "TRY"},
        "ISDMR.IS": {"name": "İskenderun Demir ve Çelik", "unit": "TRY"},
        "ISFIN.IS": {"name": "İş Finansal Kiralama", "unit": "TRY"},
        "ISGSY.IS": {"name": "İş Girişim Sermayesi", "unit": "TRY"},
        "ISKPL.IS": {"name": "Işık Plastik", "unit": "TRY"},
        "ISYAT.IS": {"name": "İş Yatırım Ortaklığı", "unit": "TRY"},
        "ITTFH.IS": {"name": "İttifak Holding", "unit": "TRY"},
        "IZENR.IS": {"name": "İzdemir Enerji", "unit": "TRY"},
        "IZFAS.IS": {"name": "İzmir Fırça", "unit": "TRY"},
        "IZINV.IS": {"name": "İz Yatırım Holding", "unit": "TRY"},
        "IZMDC.IS": {"name": "İzmir Demir Çelik", "unit": "TRY"},
        "JANTS.IS": {"name": "Jantsa", "unit": "TRY"},
        "KAPLM.IS": {"name": "Kaplamin Ambalaj", "unit": "TRY"},
        "KAREL.IS": {"name": "Karel Elektronik", "unit": "TRY"},
        "KARSN.IS": {"name": "Karsan Otomotiv", "unit": "TRY"},
        "KARTN.IS": {"name": "Kartonsan", "unit": "TRY"},
        "KARYE.IS": {"name": "Kartal Yenilenebilir Enerji", "unit": "TRY"},
        "KATMR.IS": {"name": "Katmerciler", "unit": "TRY"},
        "KENT.IS": {"name": "Kent Gıda", "unit": "TRY"},
        "KERVN.IS": {"name": "Kervansaray Yatırım Holding", "unit": "TRY"},
        "KERVT.IS": {"name": "Kerevitaş", "unit": "TRY"},
        "KFEIN.IS": {"name": "Kafein Yazılım", "unit": "TRY"},
        "KGYO.IS": {"name": "Koray GYO", "unit": "TRY"},
        "KLKIM.IS": {"name": "Kalekim", "unit": "TRY"},
        "KLNMA.IS": {"name": "Kalkınma Bankası", "unit": "TRY"},
        "KLRHO.IS": {"name": "Kiler Holding", "unit": "TRY"},
        "KLSER.IS": {"name": "Kaleseramik", "unit": "TRY"},
        "KLSYN.IS": {"name": "Koleksiyon Mobilya", "unit": "TRY"},
        "KMPUR.IS": {"name": "Kimteks Poliüretan", "unit": "TRY"},
        "KONKA.IS": {"name": "Konya Kağıt", "unit": "TRY"},
        "KRPLS.IS": {"name": "Koroplast", "unit": "TRY"},
        "KSTUR.IS": {"name": "Kuştur Kuşadası Turizm", "unit": "TRY"},
        "KTLEV.IS": {"name": "Katılımevim", "unit": "TRY"},
        "KTSKR.IS": {"name": "Kütahya Şeker Fabrikası", "unit": "TRY"},
        "KUTPO.IS": {"name": "Kütahya Porselen", "unit": "TRY"},
        "KUYAS.IS": {"name": "Kuyaş Yatırım", "unit": "TRY"},
        "LIDER.IS": {"name": "Lider Faktoring", "unit": "TRY"},
        "LIDFA.IS": {"name": "Lider Faktoring", "unit": "TRY"},
        "LKMNH.IS": {"name": "Lokman Hekim", "unit": "TRY"},
        "LUKSK.IS": {"name": "Lüks Kadife", "unit": "TRY"},
        "MAALT.IS": {"name": "Marmaris Altınyunus", "unit": "TRY"},
        "MACKO.IS": {"name": "Maçkolik", "unit": "TRY"},
        "MAKTK.IS": {"name": "Makina Takım", "unit": "TRY"},
        "MANAS.IS": {"name": "Manas Enerji Yönetimi", "unit": "TRY"},
        "MARTI.IS": {"name": "Martı Otel", "unit": "TRY"},
        "MERIT.IS": {"name": "Merit Turizm", "unit": "TRY"},
        "MERCN.IS": {"name": "Mercan Kimya", "unit": "TRY"},
        "METRO.IS": {"name": "Metro Yatırım Holding", "unit": "TRY"},
        "MHRGY.IS": {"name": "MHR GYO", "unit": "TRY"},
        "MNDRS.IS": {"name": "Menderes Tekstil", "unit": "TRY"},
        "MNDTR.IS": {"name": "Mondi Turkey", "unit": "TRY"},
        "MOBTL.IS": {"name": "Mobiltel", "unit": "TRY"},
        "MTRKS.IS": {"name": "Matriks Bilgi Dağıtım", "unit": "TRY"},
        "NIBAS.IS": {"name": "Niğbaş Niğde Beton", "unit": "TRY"},
        "NTGAZ.IS": {"name": "Naturelgaz", "unit": "TRY"},
        "ODINE.IS": {"name": "Odine Solutions", "unit": "TRY"},
        "ONRYT.IS": {"name": "Onur Yüksek Teknoloji", "unit": "TRY"},
        "ORCAY.IS": {"name": "Orçay", "unit": "TRY"},
        "ORMA.IS": {"name": "Orma Orman Mahsulleri", "unit": "TRY"},
        "OSTIM.IS": {"name": "Ostim Endüstriyel", "unit": "TRY"},
        "OYLUM.IS": {"name": "Oylum Sınai Yatırımlar", "unit": "TRY"},
        "OZRDN.IS": {"name": "Özerden Plastik", "unit": "TRY"},
        "PAGYO.IS": {"name": "Panora GYO", "unit": "TRY"},
        "PARSN.IS": {"name": "Parsan", "unit": "TRY"},
        "PEKGY.IS": {"name": "Peker GYO", "unit": "TRY"},
        "PENGD.IS": {"name": "Penguen Gıda", "unit": "TRY"},
        "PINSU.IS": {"name": "Pınar Su", "unit": "TRY"},
        "PKART.IS": {"name": "Plastikkart", "unit": "TRY"},
        "PLTUR.IS": {"name": "Platform Turizm", "unit": "TRY"},
        "PNLSN.IS": {"name": "Panelsan", "unit": "TRY"},
        "POLHO.IS": {"name": "Polisan Holding", "unit": "TRY"},
        "PRDGS.IS": {"name": "Pardus Girişim", "unit": "TRY"},
        "PSDTC.IS": {"name": "Pergamon Status", "unit": "TRY"},
        "QUAGR.IS": {"name": "Qua Granite", "unit": "TRY"},
        "RALYH.IS": {"name": "Ral Yatırım Holding", "unit": "TRY"},
        "RAYSG.IS": {"name": "Ray Sigorta", "unit": "TRY"},
        "RHEAG.IS": {"name": "Rhea Girişim Sermayesi", "unit": "TRY"},
        "RODRG.IS": {"name": "Rodrigo Tekstil", "unit": "TRY"},
        "RTALB.IS": {"name": "RTA Laboratuvarları", "unit": "TRY"},
        "SAFKR.IS": {"name": "Safkar", "unit": "TRY"},
        "SAMAT.IS": {"name": "Saray Matbaacılık", "unit": "TRY"},
        "SANFM.IS": {"name": "Sanifoam Sünger", "unit": "TRY"},
        "SANKO.IS": {"name": "Sanko Pazarlama", "unit": "TRY"},
        "SANEL.IS": {"name": "San-El Mühendislik", "unit": "TRY"},
        "SARKY.IS": {"name": "Sarkuysan", "unit": "TRY"},
        "SAYAS.IS": {"name": "Say Yenilenebilir Enerji", "unit": "TRY"},
        "SEGMN.IS": {"name": "Seğmen Kardeşler Gıda", "unit": "TRY"},
        "SEKFK.IS": {"name": "Şeker Finansal Kiralama", "unit": "TRY"},
        "SEKUR.IS": {"name": "Sekuro Plastik", "unit": "TRY"},
        "SEYKM.IS": {"name": "Seyitler Kimya", "unit": "TRY"},
        "SILVR.IS": {"name": "Silverline Ankastre", "unit": "TRY"},
        "SKYLP.IS": {"name": "Skyalp Finansal Teknolojiler", "unit": "TRY"},
        "SKYMD.IS": {"name": "Şeker Yatırım Menkul Değerler", "unit": "TRY"},
        "SMRVA.IS": {"name": "SMRVA", "unit": "TRY"},
        "SNICA.IS": {"name": "Sanica Isı", "unit": "TRY"},
        "SNKRN.IS": {"name": "Senkron Siber Güvenlik", "unit": "TRY"},
        "SODSN.IS": {"name": "SODAŞ Sodyum Sanayii", "unit": "TRY"},
        "SONME.IS": {"name": "Sönmez Filament", "unit": "TRY"},
        "SUMAS.IS": {"name": "Sumaş Suni Tahta", "unit": "TRY"},
        "SURGY.IS": {"name": "Sur Tatil Evleri GYO", "unit": "TRY"},
        "TATEN.IS": {"name": "Tatlıpınar Enerji", "unit": "TRY"},
        "TEKTU.IS": {"name": "Tek-Art Turizm", "unit": "TRY"},
        "TERA.IS": {"name": "Tera Yatırım", "unit": "TRY"},
        "TGSAS.IS": {"name": "TGS Dış Ticaret", "unit": "TRY"},
        "TIRE.IS": {"name": "Mondi Tire Kutsan", "unit": "TRY"},
        "TMPOL.IS": {"name": "Temapol Polimer Plastik", "unit": "TRY"},
        "TNZTP.IS": {"name": "Tapdi Oksijen", "unit": "TRY"},
        "TRILC.IS": {"name": "Türk İlaç Serum", "unit": "TRY"},
        "TSPOR.IS": {"name": "Trabzonspor Sportif", "unit": "TRY"},
        "TUCLK.IS": {"name": "Tuğçelik", "unit": "TRY"},
        "TUKAS.IS": {"name": "Tukaş", "unit": "TRY"},
        "TUREX.IS": {"name": "Tureks Turizm", "unit": "TRY"},
        "UFUK.IS": {"name": "Ufuk Yatırım", "unit": "TRY"},
        "ULAS.IS": {"name": "Ulaşlar Turizm", "unit": "TRY"},
        "ULUSE.IS": {"name": "Ulusoy Elektrik", "unit": "TRY"},
        "USAK.IS": {"name": "Uşak Seramik", "unit": "TRY"},
        "VANGD.IS": {"name": "Vanet Gıda", "unit": "TRY"},
        "VBTYZ.IS": {"name": "VBT Yazılım", "unit": "TRY"},
        "VERTU.IS": {"name": "Verusa Turizm", "unit": "TRY"},
        "VKFYO.IS": {"name": "Vakıf Menkul Kıymet Yatırım Ortaklığı", "unit": "TRY"},
        "YAPRK.IS": {"name": "Yaprak Süt", "unit": "TRY"},
        "YAYLA.IS": {"name": "Yayla Agro Gıda", "unit": "TRY"},
        "YBTAS.IS": {"name": "Yibitaş", "unit": "TRY"},
        "YGGYO.IS": {"name": "Yeni Gimat GYO", "unit": "TRY"},
        "YGYO.IS": {"name": "Yeşil GYO", "unit": "TRY"},
        "YKSLN.IS": {"name": "Yükselen Çelik", "unit": "TRY"},
        "YUNSA.IS": {"name": "Yünsa", "unit": "TRY"},
        "YYLGD.IS": {"name": "Yayla Gıda", "unit": "TRY"},
        "ZEDUR.IS": {"name": "Zedur Enerji", "unit": "TRY"},
        "ZRGYO.IS": {"name": "Ziraat GYO", "unit": "TRY"},


        # ═══════════════════════════════════════
        # ABD — Mega-Cap Teknoloji
        # ═══════════════════════════════════════
        "AAPL":      {"name": "Apple",             "unit": "USD"},
        "MSFT":      {"name": "Microsoft",         "unit": "USD"},
        "GOOGL":     {"name": "Alphabet (Google)", "unit": "USD"},
        "AMZN":      {"name": "Amazon",            "unit": "USD"},
        "NVDA":      {"name": "NVIDIA",            "unit": "USD"},
        "META":      {"name": "Meta (Facebook)",   "unit": "USD"},
        "TSLA":      {"name": "Tesla",             "unit": "USD"},
        "AVGO":      {"name": "Broadcom",          "unit": "USD"},
        "AMD":       {"name": "AMD",               "unit": "USD"},
        "INTC":      {"name": "Intel",             "unit": "USD"},
        "CRM":       {"name": "Salesforce",        "unit": "USD"},
        "ORCL":      {"name": "Oracle",            "unit": "USD"},
        "ADBE":      {"name": "Adobe",             "unit": "USD"},
        "NFLX":      {"name": "Netflix",           "unit": "USD"},
        "CSCO":      {"name": "Cisco",             "unit": "USD"},
        "QCOM":      {"name": "Qualcomm",          "unit": "USD"},
        "TXN":       {"name": "Texas Instruments", "unit": "USD"},
        "IBM":       {"name": "IBM",               "unit": "USD"},
        "NOW":       {"name": "ServiceNow",        "unit": "USD"},
        "PANW":      {"name": "Palo Alto",         "unit": "USD"},
        "MU":        {"name": "Micron",            "unit": "USD"},
        "PLTR":      {"name": "Palantir",          "unit": "USD"},
        "SHOP":      {"name": "Shopify",           "unit": "USD"},
        "UBER":      {"name": "Uber",              "unit": "USD"},
        "SNOW":      {"name": "Snowflake",         "unit": "USD"},
        "CRWD":      {"name": "CrowdStrike",       "unit": "USD"},
        "ARM":       {"name": "Arm Holdings",      "unit": "USD"},
        "ADP":       {"name": "ADP",               "unit": "USD"},
        "INTU":      {"name": "Intuit",            "unit": "USD"},
        # ═══════════════════════════════════════
        # ABD — Finans & Sağlık & Tüketim
        # ═══════════════════════════════════════
        "JPM":       {"name": "JPMorgan Chase",    "unit": "USD"},
        "V":         {"name": "Visa",              "unit": "USD"},
        "MA":        {"name": "Mastercard",        "unit": "USD"},
        "JNJ":       {"name": "Johnson & Johnson", "unit": "USD"},
        "UNH":       {"name": "UnitedHealth",      "unit": "USD"},
        "LLY":       {"name": "Eli Lilly",         "unit": "USD"},
        "PG":        {"name": "Procter & Gamble",  "unit": "USD"},
        "KO":        {"name": "Coca-Cola",         "unit": "USD"},
        "PEP":       {"name": "PepsiCo",           "unit": "USD"},
        "WMT":       {"name": "Walmart",           "unit": "USD"},
        "COST":      {"name": "Costco",            "unit": "USD"},
        "HD":        {"name": "Home Depot",        "unit": "USD"},
        "DIS":       {"name": "Disney",            "unit": "USD"},
        "BAC":       {"name": "Bank of America",   "unit": "USD"},
        "WFC":       {"name": "Wells Fargo",       "unit": "USD"},
        "GS":        {"name": "Goldman Sachs",     "unit": "USD"},
        "MS":        {"name": "Morgan Stanley",    "unit": "USD"},
        "BLK":       {"name": "BlackRock",         "unit": "USD"},
        "BRK":       {"name": "Berkshire",         "unit": "USD"},
        "PFE":       {"name": "Pfizer",            "unit": "USD"},
        "MRK":       {"name": "Merck",             "unit": "USD"},
        "ABBV":      {"name": "AbbVie",            "unit": "USD"},
        "TMO":       {"name": "Thermo Fisher",     "unit": "USD"},
        "ABT":       {"name": "Abbott",            "unit": "USD"},
        "NKE":       {"name": "Nike",              "unit": "USD"},
        "MCD":       {"name": "McDonald's",        "unit": "USD"},
        "SBUX":      {"name": "Starbucks",         "unit": "USD"},
        "CMCSA":     {"name": "Comcast",           "unit": "USD"},
        "T":         {"name": "AT&T",              "unit": "USD"},
        # ═══════════════════════════════════════
        # ABD — Enerji & Sanayi
        # ═══════════════════════════════════════
        "XOM":       {"name": "ExxonMobil",        "unit": "USD"},
        "CVX":       {"name": "Chevron",           "unit": "USD"},
        "BA":        {"name": "Boeing",            "unit": "USD"},
        "CAT":       {"name": "Caterpillar",       "unit": "USD"},
        "GE":        {"name": "GE Aerospace",      "unit": "USD"},
        "RTX":       {"name": "RTX",               "unit": "USD"},
        "LMT":       {"name": "Lockheed Martin",   "unit": "USD"},
        "NOC":       {"name": "Northrop Grumman",  "unit": "USD"},
        "DE":        {"name": "Deere",             "unit": "USD"},
        "HON":       {"name": "Honeywell",         "unit": "USD"},
        "UNP":       {"name": "Union Pacific",     "unit": "USD"},
        "COP":       {"name": "ConocoPhillips",    "unit": "USD"},
        "SLB":       {"name": "Schlumberger",      "unit": "USD"},
        "EOG":       {"name": "EOG Resources",     "unit": "USD"},
        # ═══════════════════════════════════════
        # Küresel — Avrupa
        # ═══════════════════════════════════════
        "ASML":      {"name": "ASML Holding",      "unit": "EUR"},
        "NVO":       {"name": "Novo Nordisk",      "unit": "USD"},
        "SAP":       {"name": "SAP SE",            "unit": "USD"},
        "SHEL":      {"name": "Shell",             "unit": "USD"},
        "AZN":       {"name": "AstraZeneca",       "unit": "USD"},
        "UL":        {"name": "Unilever",          "unit": "USD"},
        "TTE":       {"name": "TotalEnergies",     "unit": "USD"},
        "NVS":       {"name": "Novartis",          "unit": "USD"},
        "ROG":       {"name": "Roche",             "unit": "USD"},
        "BP":        {"name": "BP",                "unit": "USD"},
        "RIO":       {"name": "Rio Tinto",         "unit": "USD"},
        "HSBC":      {"name": "HSBC",              "unit": "USD"},
        "UBS":       {"name": "UBS",               "unit": "USD"},
        "SAN":       {"name": "Santander",         "unit": "USD"},
        "ING":       {"name": "ING",               "unit": "USD"},
        "GSK":       {"name": "GSK",               "unit": "USD"},
        "DTEGY":     {"name": "Deutsche Telekom",  "unit": "USD"},
        "BMWYY":     {"name": "BMW",               "unit": "USD"},
        "VWAGY":     {"name": "Volkswagen",        "unit": "USD"},
        "NSRGY":     {"name": "Nestle",            "unit": "USD"},
        "LRLCY":     {"name": "L'Oreal",           "unit": "USD"},
        "MC":        {"name": "LVMH",              "unit": "USD"},
        # ═══════════════════════════════════════
        # Küresel — Asya-Pasifik
        # ═══════════════════════════════════════
        "TSM":       {"name": "TSMC",              "unit": "USD"},
        "005930.KS": {"name": "Samsung",           "unit": "KRW"},
        "BABA":      {"name": "Alibaba",           "unit": "USD"},
        "PDD":       {"name": "PDD (Pinduoduo)",   "unit": "USD"},
        "TM":        {"name": "Toyota Motor",      "unit": "USD"},
        "SONY":      {"name": "Sony Group",        "unit": "USD"},
        "BHP":       {"name": "BHP Group",         "unit": "USD"},
        "HMC":       {"name": "Honda",             "unit": "USD"},
        "NTDOY":     {"name": "Nintendo",          "unit": "USD"},
        "MUFG":      {"name": "Mitsubishi UFJ",    "unit": "USD"},
        "SMFG":      {"name": "Sumitomo Mitsui",   "unit": "USD"},
        "MELI":      {"name": "MercadoLibre",      "unit": "USD"},
        "INFY":      {"name": "Infosys",           "unit": "USD"},
        "HDB":       {"name": "HDFC Bank",         "unit": "USD"},
        "IBN":       {"name": "ICICI Bank",        "unit": "USD"},

        # ── BIST Ek Paket ─────────────────────────────
        "ANSGR.IS": {"name": "Anadolu Sigorta", "unit": "TRY"},
        "AKGRT.IS": {"name": "Aksigorta", "unit": "TRY"},
        "AGESA.IS": {"name": "Agesa Hayat", "unit": "TRY"},
        "ANHYT.IS": {"name": "Anadolu Hayat", "unit": "TRY"},
        "ISMEN.IS": {"name": "İş Yatırım", "unit": "TRY"},
        "OYYAT.IS": {"name": "Oyak Yatırım", "unit": "TRY"},
        "GLBMD.IS": {"name": "Global Menkul", "unit": "TRY"},
        "GWIND.IS": {"name": "Galata Wind", "unit": "TRY"},
        "NATEN.IS": {"name": "Naturel Enerji", "unit": "TRY"},
        "YEOTK.IS": {"name": "Yeo Teknoloji", "unit": "TRY"},
        "AKFYE.IS": {"name": "Akfen Yenilenebilir", "unit": "TRY"},
        "BIOEN.IS": {"name": "Biotrend", "unit": "TRY"},
        "SUWEN.IS": {"name": "Suwen", "unit": "TRY"},
        "KOTON.IS": {"name": "Koton", "unit": "TRY"},
        "BIGCH.IS": {"name": "BigChefs", "unit": "TRY"},
        "KRONT.IS": {"name": "Kron Teknoloji", "unit": "TRY"},
        "LINK.IS": {"name": "Link Bilgisayar", "unit": "TRY"},
        "DESPC.IS": {"name": "Despec", "unit": "TRY"},
        "INDES.IS": {"name": "İndeks Bilgisayar", "unit": "TRY"},
        "PENTA.IS": {"name": "Penta Teknoloji", "unit": "TRY"},
        "ALARK.IS": {"name": "Alarko Holding", "unit": "TRY"},
        "GLYHO.IS": {"name": "Global Yatırım", "unit": "TRY"},
        "IHLAS.IS": {"name": "İhlas Holding", "unit": "TRY"},
        "NTHOL.IS": {"name": "Net Holding", "unit": "TRY"},
        "GSDHO.IS": {"name": "GSD Holding", "unit": "TRY"},
        "AKCNS.IS": {"name": "Akçansa", "unit": "TRY"},
        "BOBET.IS": {"name": "Boğaziçi Beton", "unit": "TRY"},
        "KRVGD.IS": {"name": "Kervan Gıda", "unit": "TRY"},
        "ULUUN.IS": {"name": "Ulusoy Un", "unit": "TRY"},
        "PNSUT.IS": {"name": "Pınar Süt", "unit": "TRY"},
        "PETUN.IS": {"name": "Pınar Et", "unit": "TRY"},
        "BANVT.IS": {"name": "Banvit", "unit": "TRY"},
        "GOZDE.IS": {"name": "Gözde Girişim", "unit": "TRY"},
        "GOLTS.IS": {"name": "Göltaş Çimento", "unit": "TRY"},
        "NUGYO.IS": {"name": "Nurol GYO", "unit": "TRY"},
        "OZGYO.IS": {"name": "Özderici GYO", "unit": "TRY"},
        "RYGYO.IS": {"name": "Reysaş GYO", "unit": "TRY"},
        "KLGYO.IS": {"name": "Kiler GYO", "unit": "TRY"},
        "DAPGM.IS": {"name": "DAP GYO", "unit": "TRY"},
        "ORGE.IS": {"name": "Orge Enerji", "unit": "TRY"},
        
        # ── ABD Mega/Quality ──────────────────────────
        "AMAT": {"name": "Applied Materials", "unit": "USD"},
        "LRCX": {"name": "Lam Research", "unit": "USD"},
        "KLAC": {"name": "KLA", "unit": "USD"},
        "ANET": {"name": "Arista Networks", "unit": "USD"},
        "MSI": {"name": "Motorola Solutions", "unit": "USD"},
        "CDNS": {"name": "Cadence", "unit": "USD"},
        "SNPS": {"name": "Synopsys", "unit": "USD"},
        "FTNT": {"name": "Fortinet", "unit": "USD"},
        "NET": {"name": "Cloudflare", "unit": "USD"},
        "DDOG": {"name": "Datadog", "unit": "USD"},
        "ZS": {"name": "Zscaler", "unit": "USD"},
        "MDB": {"name": "MongoDB", "unit": "USD"},
        "TEAM": {"name": "Atlassian", "unit": "USD"},
        "PYPL": {"name": "PayPal", "unit": "USD"},
        "SQ": {"name": "Block", "unit": "USD"},
        "COIN": {"name": "Coinbase", "unit": "USD"},
        "KKR": {"name": "KKR", "unit": "USD"},
        "BX": {"name": "Blackstone", "unit": "USD"},
        "SPGI": {"name": "S&P Global", "unit": "USD"},
        "ICE": {"name": "Intercontinental Exchange", "unit": "USD"},
        "CME": {"name": "CME Group", "unit": "USD"},
        "MSCI": {"name": "MSCI", "unit": "USD"},
        "MO": {"name": "Altria", "unit": "USD"},
        "PM": {"name": "Philip Morris", "unit": "USD"},
        "ELV": {"name": "Elevance Health", "unit": "USD"},
        "CI": {"name": "Cigna", "unit": "USD"},
        "CVS": {"name": "CVS Health", "unit": "USD"},
        "MDT": {"name": "Medtronic", "unit": "USD"},
        "ISRG": {"name": "Intuitive Surgical", "unit": "USD"},
        "SYK": {"name": "Stryker", "unit": "USD"},
        "BDX": {"name": "Becton Dickinson", "unit": "USD"},
        "ZTS": {"name": "Zoetis", "unit": "USD"},
        "LOW": {"name": "Lowe's", "unit": "USD"},
        "TGT": {"name": "Target", "unit": "USD"},
        "ROST": {"name": "Ross Stores", "unit": "USD"},
        "TJX": {"name": "TJX", "unit": "USD"},
        "BKNG": {"name": "Booking", "unit": "USD"},
        "ABNB": {"name": "Airbnb", "unit": "USD"},
        "MAR": {"name": "Marriott", "unit": "USD"},
        "HLT": {"name": "Hilton", "unit": "USD"},
        
        # ── ABD Sanayi / Enerji / Ulaştırma ───────────
        "ETN": {"name": "Eaton", "unit": "USD"},
        "PH": {"name": "Parker Hannifin", "unit": "USD"},
        "ITW": {"name": "Illinois Tool Works", "unit": "USD"},
        "EMR": {"name": "Emerson", "unit": "USD"},
        "ROK": {"name": "Rockwell Automation", "unit": "USD"},
        "JCI": {"name": "Johnson Controls", "unit": "USD"},
        "TT": {"name": "Trane Technologies", "unit": "USD"},
        "CSX": {"name": "CSX", "unit": "USD"},
        "NSC": {"name": "Norfolk Southern", "unit": "USD"},
        "FDX": {"name": "FedEx", "unit": "USD"},
        "UPS": {"name": "UPS", "unit": "USD"},
        "DAL": {"name": "Delta", "unit": "USD"},
        "UAL": {"name": "United Airlines", "unit": "USD"},
        "AAL": {"name": "American Airlines", "unit": "USD"},
        "OXY": {"name": "Occidental", "unit": "USD"},
        "MPC": {"name": "Marathon Petroleum", "unit": "USD"},
        "PSX": {"name": "Phillips 66", "unit": "USD"},
        "VLO": {"name": "Valero", "unit": "USD"},
        "KMI": {"name": "Kinder Morgan", "unit": "USD"},
        "WMB": {"name": "Williams Companies", "unit": "USD"},
        
        # ── Avrupa / Global ADR ───────────────────────
        "RACE": {"name": "Ferrari", "unit": "USD"},
        "STLA": {"name": "Stellantis", "unit": "USD"},
        "MBGYY": {"name": "Mercedes-Benz", "unit": "USD"},
        "PRYMY": {"name": "Prysmian", "unit": "USD"},
        "SNY": {"name": "Sanofi", "unit": "USD"},
        "GLE": {"name": "Societe Generale", "unit": "USD"},
        "BNPQY": {"name": "BNP Paribas", "unit": "USD"},
        "DB": {"name": "Deutsche Bank", "unit": "USD"},
        "BBVA": {"name": "BBVA", "unit": "USD"},
        "ISP": {"name": "Intesa Sanpaolo", "unit": "USD"},
        "RHHBY": {"name": "Roche Holding", "unit": "USD"},
        "NOVN": {"name": "Novartis ADR Alt", "unit": "USD"},
        "SI": {"name": "Siemens ADR", "unit": "USD"},
        "AIQUY": {"name": "Air Liquide", "unit": "USD"},
        "DANOY": {"name": "Danone", "unit": "USD"},
        "HEINY": {"name": "Heineken", "unit": "USD"},
        "ADRNY": {"name": "Koninklijke Ahold", "unit": "USD"},
        "FERG": {"name": "Ferguson", "unit": "USD"},
        "RELX": {"name": "RELX", "unit": "USD"},
        "EXPGY": {"name": "Experian", "unit": "USD"},
        
        # ── Asya / LatAm Global ───────────────────────
        "BIDU": {"name": "Baidu", "unit": "USD"},
        "JD": {"name": "JD.com", "unit": "USD"},
        "NTES": {"name": "NetEase", "unit": "USD"},
        "TME": {"name": "Tencent Music", "unit": "USD"},
        "LI": {"name": "Li Auto", "unit": "USD"},
        "NIO": {"name": "NIO", "unit": "USD"},
        "XPEV": {"name": "XPeng", "unit": "USD"},
        "BYDDY": {"name": "BYD", "unit": "USD"},
        "PBR": {"name": "Petrobras", "unit": "USD"},
        "VALE": {"name": "Vale", "unit": "USD"},
        "ITUB": {"name": "Itau Unibanco", "unit": "USD"},
        "NU": {"name": "Nubank", "unit": "USD"},
        "GRAB": {"name": "Grab", "unit": "USD"},
        "SE": {"name": "Sea Ltd", "unit": "USD"},
        "YUMC": {"name": "Yum China", "unit": "USD"},
        "ASX": {"name": "ASE Technology", "unit": "USD"},
        "CHT": {"name": "Chunghwa Telecom", "unit": "USD"},
        "PKX": {"name": "POSCO", "unit": "USD"},
        "KB": {"name": "KB Financial", "unit": "USD"},
        "SHG": {"name": "Shinhan Financial", "unit": "USD"},
        "TCEHY": {"name": "Tencent", "unit": "USD"},
        "BBD": {"name": "Banco Bradesco", "unit": "USD"},
        "CIB": {"name": "Bancolombia", "unit": "USD"},
        "YPF": {"name": "YPF", "unit": "USD"},
        "GGB": {"name": "Gerdau", "unit": "USD"},
        "SID": {"name": "CSN", "unit": "USD"},
        "AU": {"name": "AngloGold Ashanti", "unit": "USD"},
        "GFI": {"name": "Gold Fields", "unit": "USD"},
        "SBSW": {"name": "Sibanye-Stillwater", "unit": "USD"},
        "BAP": {"name": "Credicorp", "unit": "USD"},
        "EC": {"name": "Ecopetrol", "unit": "USD"},
        "PAM": {"name": "Pampa Energia", "unit": "USD"},
        "WDS": {"name": "Woodside Energy", "unit": "USD"},
        "GOLD": {"name": "Barrick Gold", "unit": "USD"},
        "EXK": {"name": "Endeavour Silver", "unit": "USD"},
        "PAAS": {"name": "Pan American Silver", "unit": "USD"},
        "SCCO": {"name": "Southern Copper", "unit": "USD"},
        "BTI": {"name": "British American Tobacco", "unit": "USD"},
        "MRNA": {"name": "Moderna", "unit": "USD"},
        "REGN": {"name": "Regeneron", "unit": "USD"},
        "VRTX": {"name": "Vertex Pharma", "unit": "USD"},
        "GILD": {"name": "Gilead", "unit": "USD"},
        "AMGN": {"name": "Amgen", "unit": "USD"},
        "ADSK": {"name": "Autodesk", "unit": "USD"},
        "WDAY": {"name": "Workday", "unit": "USD"},
        "DOCU": {"name": "DocuSign", "unit": "USD"},
        "OKTA": {"name": "Okta", "unit": "USD"},
        "MSTR": {"name": "MicroStrategy", "unit": "USD"},
        "RBLX": {"name": "Roblox", "unit": "USD"},
        "HUBS": {"name": "HubSpot", "unit": "USD"},
        "TTD": {"name": "Trade Desk", "unit": "USD"},
        "SPOT": {"name": "Spotify", "unit": "USD"},
        "ADDYY": {"name": "Adidas ADR", "unit": "USD"},
        "SCHYY": {"name": "Schneider Electric ADR", "unit": "USD"},
        "EADSY": {"name": "Airbus ADR", "unit": "USD"},
        "RNLSY": {"name": "Renault ADR", "unit": "USD"},
        "VLVLY": {"name": "Volvo ADR", "unit": "USD"},
        "ALIZY": {"name": "Allianz ADR", "unit": "USD"},
        "BAYRY": {"name": "Bayer ADR", "unit": "USD"},
        "IFNNY": {"name": "Infineon ADR", "unit": "USD"},
        "BASFY": {"name": "BASF ADR", "unit": "USD"},
        "DHLGY": {"name": "DHL ADR", "unit": "USD"},
    }
}

ALL_YF_GROUPS = [
    COMMODITIES_ENERGY,
    COMMODITIES_METALS,
    COMMODITIES_AGRICULTURE,
    INDUSTRIAL,
    CURRENCIES,
    BONDS,
    INDICES,
    CRYPTO,
    STOCKS,
]
